#!/bin/csh -f

set TOUCH = ORIG
if ( ! -e configure.wps ) then
	touch configure.wps
	set TOUCH = TOUCH
endif

set nonomatch

set DIRS = ( geogrid ungrib metgrid )
set DIRS = ( geogrid        metgrid )
foreach dir ( $DIRS )
	if ( -d $dir ) then 
		( cd $dir ; make -i TARGET="${dir}.exe" clean )
	endif
end

if ( -e GRIBFILE.AAA ) then
	/bin/rm -f GRIBFILE.[A-Z][A-Z][A-Z]
endif

if ( -e Vtable ) then
	/bin/rm -f Vtable
endif

if ( -e geo_{em,nmm}.d[0-9][0-9].{nc,bin,grib} ) then
	/bin/rm -f geo_{em,nmm}.d[0-9][0-9].{nc,bin,grib}
endif

if ( -e geogrid.log ) then
	/bin/rm -f geogrid.log
endif

if ( -e metgrid.log ) then
	/bin/rm -f metgrid.log
endif

if ( "$1" == '-a' ) then
	/bin/rm -rf ./netcdf_links
	foreach dir ( $DIRS )
		if ( -d $dir ) then 
			( cd $dir ; make -i TARGET="${dir}.exe" superclean )
		endif
	end
	if ( -f configure.wps ) then
		/bin/cp configure.wps configure.wps.backup
		/bin/rm -f configure.wps
	endif
endif

if ( ( $TOUCH == TOUCH ) && ( -e configure.wps ) ) then
	/bin/rm -f configure.wps
endif
