#!/bin/sh
# Meant to be run at the top level
./arch/configure_reader.py \
  arch/configure.defaults  \
  cmake/template/arch_config.cmake \
  wps_config.cmake \
  CMakeLists.txt

WRF_DIR=
if [ ! -z $1 ]; then
  WRF_DIR=-DWRF_DIR="$1"
fi

# Now run cmake
mkdir -p _build/
cd _build
cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/../run -DCMAKE_TOOLCHAIN_FILE=$PWD/..//wps_config.cmake ${WRF_DIR}
# cmake -S . -B _build 